package petc

func PQuiz9() {
	//SYNAP + SOFT = WANTS + YOU
	//SEND +MORE = MONEY
	//EMAIL= SPAM + SPAM + SPAM + SPAM + SPAM + SPAM
	//FORTY +TEN+ TEN= SIXTY
	//NUMBER = SQUARE + SQUARE + SQUARE + SQUARE
	//SEVENTY = FIVE + SEVEN + ELEVEN + TWELVE + FIFTEEN + TWENTY
	//MANET + MATISSE + MIRO + MONET + RENOIR = ARTISTS
	//SIX+SIX+SIX = NINE + NINE
	//ABCDE*F=GGGGGG
	//ADAM+AND+EVE=MOVED
	//FIVE+FIVE+NINE+ELEVEN=THIRTY
	//CROSS+ROADS=DANGER
	//USE + LESS = KIDDY
	//BILL + WILLIAM + MONICA = CLINTON
	//GREEN + ORANGE = COLORS
	//CEZANNE + MANET + MATISSE = ARTISTS
	//OLD+SALT+TOLD+TALL=TALES
	//COFFEE + COFFEE + COFFEE = THEOREM
	//SEND * ME = EMAIL
	//POWER = YOUR + SHOW
	//ALLEN = K * JEON
}